services:
    app:
        build: .
        container_name: tiger-test-task
        restart: always
        ports:
            - "8000:8000"
        working_dir: /var/www
        volumes:
          - .:/var/www
          - ./storage/logs:/var/www/storage/logs
        environment:
            APP_ENV: production
            APP_DEBUG: "false"
